sudo: required # tell Travis that we need super user level permission to execute this build
services:
  - docker # tell Travis that we need the Docker CLI pre-installed

before_install:
  - docker build -t xian0120/docker-react -f Dockerfile.dev . # Tell Travis to build the image first

script:
  - docker run -e CI=true xian0120/docker-react npm run test
