version: "3"
services:
  web:
    build:
      context: . # to specify where the files and folders for this image to be pulled from, in this case it is the current working directory
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # telling docker do not try to map a folder up against app/node_modules
      - .:/app # map the current folder outside the container to the 'app' folder inside the container
  tests: # for running tests (npm run test)
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
